# codemagic.yaml
workflows:
  ios-workflow:
    name: Build iOS Lilica
    environment:
      name: default
      flutter: "3.38.4"  # OU "3.25.0" se 3.38.4 não existir
      xcode: latest
      cocoapods: default
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          
    scripts:
      - name: Setup Flutter
        script: |
          # Verifica e instala versão correta
          if ! flutter --version | grep -q "3.38.4"; then
            echo "Instalando Flutter 3.38.4..."
            flutter channel stable
            flutter upgrade --force
          fi
          flutter --version
          
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
          
      - name: Install iOS dependencies
        script: |
          cd ios
          pod install --repo-update
          cd ..
          
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
          
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ios/Runner.app
      
    publishing:
      email:
        recipients:
          - seu-email@gmail.com
        notify:
          success: true
          failure: true